on:
  workflow_run:
    workflows:
    - On pull
    types:
    - completed
jobs:
  on-failure:
    runs-on: ubuntu-24.04
    if: github.event.workflow_run.conclusion == 'failure'
    steps:
      - run: echo '${{github.event.workflow_run}}'
