on:
  workflow_run:
    workflows:
    - On pull
    types:
    - completed
jobs:
  on-failure:
    runs-on: ubuntu-24.04
    if: github.event.workflow_run.conclusion == 'failure'
    steps:
      - name: Check out the code from the pull request
        uses: actions/checkout@v4
        with:
          repository: ${{github.event.workflow_run.head_repository.full_name}}
          ref: ${{github.event.workflow_run.head_commit.id}}
          set-safe-directory: false
      - name: TODO
        run: date > bar.txt
      - run: |
          git add .
          git commit -m 'Automatic changes'
          git remote add upstream '${{ github.repository }}'
          git push upstream HEAD:untrusted-hello
